name: Release

on:
  push:
    branches: [ main ]
    
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: ls $GITHUB_WORKSPACE

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
