name: Release

on:
  push:
    branches: [ main ]
    
jobs:
  release:
    runs-on: ubuntu-latest
    env: 
      FILENAME: de.swerik.template.universal-1.0.0.tgz

    steps:
      - uses: actions/checkout@v2

      - name: Zip
        run: |
          cd Release 
          tar -czvf $FILENAME package

      -name: Test
        run: ls

      - name: Publish template
      - uses: actions/upload-artifact@v2
        with:
          name: $FILENAME
          path: Release/$FILENAME
