name: Release

on:
  push:
    branches: [ main ]
    
jobs:
  release:
    runs-on: ubuntu-latest
    env: 
      FILENAME: de.swerik.template.universal-1.0.0.tgz

    steps:
      - uses: actions/checkout@v2

      - name: Zip
        run: |
          cd Release 
          tar -czvf $FILENAME package 
          cd ..

      - name: Publish template
        run: echo Release/$FILENAME
